#!/usr/bin/env bash

go run main.go -name "Achievement" > ../../generated/bungie/datax/achievement.go
go run main.go -name "Activity" > ../../generated/bungie/datax/activity.go
go run main.go -name "ActivityGraph" > ../../generated/bungie/datax/activity_graph.go
go run main.go -name "ActivityInteractable" > ../../generated/bungie/datax/activity_interactable.go
go run main.go -name "ActivityMode" > ../../generated/bungie/datax/activity_mode.go
go run main.go -name "ActivityModifier" > ../../generated/bungie/datax/activity_modifier.go
go run main.go -name "ActivityType" > ../../generated/bungie/datax/activity_type.go
go run main.go -name "ArtDyeChannel" > ../../generated/bungie/datax/art_dye_channel.go
go run main.go -name "ArtDyeReference" > ../../generated/bungie/datax/art_dye_reference.go
go run main.go -name "Artifact" > ../../generated/bungie/datax/artifact.go
go run main.go -name "Bond" > ../../generated/bungie/datax/bond.go
go run main.go -name "BreakerType" > ../../generated/bungie/datax/breaker_type.go
go run main.go -name "CharacterCustomizationCategory" > ../../generated/bungie/datax/character_customization_category.go
go run main.go -name "CharacterCustomizationOption" > ../../generated/bungie/datax/character_customization_option.go
go run main.go -name "Checklist" > ../../generated/bungie/datax/checklist.go
go run main.go -name "Class" > ../../generated/bungie/datax/class.go
go run main.go -name "Collectible" > ../../generated/bungie/datax/collectible.go
go run main.go -name "DamageType" > ../../generated/bungie/datax/damage_type.go
go run main.go -name "Destination" > ../../generated/bungie/datax/destination.go
go run main.go -name "EnemyRace" > ../../generated/bungie/datax/enemy_race.go
go run main.go -name "EnergyType" > ../../generated/bungie/datax/energy_type.go
go run main.go -name "EntitlementOffer" > ../../generated/bungie/datax/entitlement_offer.go
go run main.go -name "EquipmentSlot" > ../../generated/bungie/datax/equipment_slot.go
go run main.go -name "Faction" > ../../generated/bungie/datax/faction.go
go run main.go -name "Gender" > ../../generated/bungie/datax/gender.go
go run main.go -name "InventoryBucket" > ../../generated/bungie/datax/inventory_bucket.go
go run main.go -name "InventoryItem" > ../../generated/bungie/datax/inventory_item.go
go run main.go -name "ItemCategory" > ../../generated/bungie/datax/item_category.go
go run main.go -name "ItemTierType" > ../../generated/bungie/datax/item_tier_type.go
go run main.go -name "Location" > ../../generated/bungie/datax/location.go
go run main.go -name "Lore" > ../../generated/bungie/datax/lore.go
go run main.go -name "MaterialRequirementSet" > ../../generated/bungie/datax/material_requirement_set.go
go run main.go -name "MedalTier" > ../../generated/bungie/datax/medal_tier.go
go run main.go -name "Milestone" > ../../generated/bungie/datax/milestone.go
#go run main.go -name "NodeStepSummary" > ../../generated/bungie/datax/node_step_summary.go
go run main.go -name "Objective" > ../../generated/bungie/datax/objective.go
go run main.go -name "Place" > ../../generated/bungie/datax/place.go
go run main.go -name "PlatformBucketMapping" > ../../generated/bungie/datax/platform_bucket_mapping.go
go run main.go -name "PlugSet" > ../../generated/bungie/datax/plug_set.go
go run main.go -name "PresentationNode" > ../../generated/bungie/datax/presentation_node.go
go run main.go -name "Progression" > ../../generated/bungie/datax/progression.go
go run main.go -name "ProgressionLevelRequirement" > ../../generated/bungie/datax/progression_level_requirement.go
go run main.go -name "ProgressionMapping" > ../../generated/bungie/datax/progression_mapping.go
go run main.go -name "Race" > ../../generated/bungie/datax/race.go
go run main.go -name "Record" > ../../generated/bungie/datax/record.go
go run main.go -name "ReportReasonCategory" > ../../generated/bungie/datax/report_reason_category.go
go run main.go -name "RewardAdjusterPointer" > ../../generated/bungie/datax/reward_adjuster_pointer.go
go run main.go -name "RewardAdjusterProgressionMap" > ../../generated/bungie/datax/reward_adjuster_progression_map.go
go run main.go -name "RewardItemList" > ../../generated/bungie/datax/reward_item_list.go
go run main.go -name "RewardMapping" > ../../generated/bungie/datax/reward_mapping.go
go run main.go -name "RewardSheet" > ../../generated/bungie/datax/reward_sheet.go
#go run main.go -name "RewardSource" > ../../generated/bungie/datax/reward_source.go
go run main.go -name "SackRewardItemList" > ../../generated/bungie/datax/sack_reward_item_list.go
go run main.go -name "SandboxPattern" > ../../generated/bungie/datax/sandbox_pattern.go
go run main.go -name "SandboxPerk" > ../../generated/bungie/datax/sandbox_perk.go
go run main.go -name "Season" > ../../generated/bungie/datax/season.go
go run main.go -name "SeasonPass" > ../../generated/bungie/datax/season_pass.go
go run main.go -name "SocketCategory" > ../../generated/bungie/datax/socket_category.go
go run main.go -name "SocketType" > ../../generated/bungie/datax/socket_type.go
go run main.go -name "Stat" > ../../generated/bungie/datax/stat.go
go run main.go -name "StatGroup" > ../../generated/bungie/datax/stat_group.go
go run main.go -name "TalentGrid" > ../../generated/bungie/datax/talent_grid.go
go run main.go -name "UnlockCountMapping" > ../../generated/bungie/datax/unlock_count_mapping.go
go run main.go -name "Unlock" > ../../generated/bungie/datax/unlock.go
go run main.go -name "UnlockEvent" > ../../generated/bungie/datax/unlock_event.go
go run main.go -name "UnlockExpressionMapping" > ../../generated/bungie/datax/unlock_expression_mapping.go
go run main.go -name "UnlockValue" > ../../generated/bungie/datax/unlock_value.go
go run main.go -name "Vendor" > ../../generated/bungie/datax/vendor.go
go run main.go -name "VendorGroup" > ../../generated/bungie/datax/vendor_group.go